### ISSUE TITLE
ac部署云函数 变量传不过去

### ISSUE THREAD

**Issue by Silentely** [Jone2008/JD#282]
尝试了好几次 后面和大佬的对比发现有些不同，不知道哪个地方出错了
第一张是大佬的
第二张是我的
第三张是变量配置
![1](https://mjj.today/temp/2101/8a74100c2bb24b9e.png)
![2](https://mjj.today/temp/2101/859416fa603d00bd.png)
![3](https://mjj.today/temp/2101/569cfe30e9ede276.png)

**Comment by Jone2008** [comment]
其实我也没同步成功，都还在研究到底哪里出错了，暂时现在我都是在手动修改云函数配置的

**Comment by Silentely** [comment]
> 其实我也没同步成功，都还在研究到底哪里出错了，暂时现在我都是在手动修改云函数配置的

我看了一下 我用其他签到的ac部署到云函数上，在云函数那边是有这个部署情况的（https://serverless.cloud.tencent.com/），但是这个jd部署却没这个应用，但是又确实生成项目了。变量却没传递。
![](https://ftp.bmp.ovh/imgs/2021/01/68cdbc403d3f568b.png)

**Comment by Jone2008** [comment]
有部署情况，但是自从云函数更新版本以后，大佬这边也做出了调整，但是效果还是不太理想。例如触发器，得删除原来的再同步过去才行，原有的触发器并不能覆盖掉。还有环境变量一直无法同步过去，不过还好好多变量例如互助码都只需设置一次即可，问题还不是很大。cookie之前同步是没问题，现在还没测试到。我也试过重新新建函数同步过去，环境变量也是空白的。所以暂时只能手动

**Comment by Silentely** [comment]
改用docker了。云函数备用  其实云函数更新还是可以 不会覆盖掉环境变量。

**Comment by Silentely** [comment]
> 有部署情况，但是自从云函数更新版本以后，大佬这边也做出了调整，但是效果还是不太理想。例如触发器，得删除原来的再同步过去才行，原有的触发器并不能覆盖掉。还有环境变量一直无法同步过去，不过还好好多变量例如互助码都只需设置一次即可，问题还不是很大。cookie之前同步是没问题，现在还没测试到。我也试过重新新建函数同步过去，环境变量也是空白的。所以暂时只能手动

大佬。问题解决了 
https://gitee.com/lxk0301/jd_scripts/pulls/120/files
